Feature/publish ros mesh
ethz-asl/infinitam pull request #7
Opened 2016-12-20 01:30 UTC by gocarlos

2016-12-20 08:49 UTC, martiwer requested changes

2016-12-20 08:49 UTC, martiwer commented on InfiniTAM/infinitam_ros_node.cpp
> +  if (true) {
Use a parameter for saving cloud to file system. Or remove the if statement.

2016-12-20 08:49 UTC, martiwer commented on InfiniTAM/infinitam_ros_node.cpp
> +        "../output_" + std::to_string(ros::Time::now().toSec()) + ".stl";
You can use `ros::package::getPath("your_package")` to get the package path.

2016-12-20 08:49 UTC, martiwer commented on InfiniTAM/infinitam_ros_node.cpp
> +    LOG(INFO) << "got point cloud";
Remove log if not needed anymore.

2016-12-20 08:49 UTC, martiwer commented on InfiniTAM/infinitam_ros_node.cpp
> +    pcl::io::saveOBJFile("../awesome_mesh.obj", *mesh_ptr_);
Give a more significant name ;) and maybe use absolute path.

2016-12-20 08:49 UTC, martiwer commented on InfiniTAM/infinitam_ros_node.cpp
> +  pcl::toROSMsg(*point_cloud_pcl, mesh_ptr_->cloud);
Why don't you use here polygon_mesh_ptr instead of mesh_ptr_ ? Replace all mesh_ptr_ in this method with polygon_mesh_ptr.

2016-12-20 08:49 UTC, martiwer commented on InfiniTAM/infinitam_ros_node.cpp
> +    // polygon_mesh_ptr->polygons[i].vertices.push_back(i * 3 + 2 + 1);
Removed outdated code.

2016-12-20 08:49 UTC, martiwer commented on InfiniTAM/infinitam_ros_node.cpp
> +       i = i + 3) {
Is this iteration correct? It is not the same as used in extractITMMeshToPolygonMesh to get the pcl point cloud from the triangleArray. Anyway, I would use this method (extractITMMeshToPclCloud) to get the pcl cloud in extractITMMeshToPolygonMesh.

2016-12-20 08:49 UTC, martiwer commented on InfiniTAM/infinitam_ros_node.cpp
> +    for (int j = 0; j < 3; ++j) {
`j < polygon_mesh_ptr->polygons[i].vertices.size()` or is the polygon always defined as triangle?

2016-12-20 10:48 UTC, gocarlos commented on InfiniTAM/infinitam_ros_node.cpp
> +    // polygon_mesh_ptr->polygons[i].vertices.push_back(i * 3 + 2 + 1);
This is not outdated code. As I tried to explain with the comment: 
OBJ. standard says that the vertices index begin with 1. Now if I start with 1 PCL Library added note more so my smallest index is 2 and I cannot view this file for example with meshlab. When sending the mesh or transforming it to a ros message I need to start again with 1 do I have to add 1 to the smallest index.

2016-12-20 10:49 UTC, gocarlos commented on InfiniTAM/infinitam_ros_node.cpp
> +    // polygon_mesh_ptr->polygons[i].vertices.push_back(i * 3 + 2 + 1);
At the end I dont want to save the mesh but only publish it, then I can just remove the lines below.

2016-12-20 10:55 UTC, gocarlos commented on InfiniTAM/infinitam_ros_node.cpp
> +    for (int j = 0; j < 3; ++j) {
In polygonMesh the polygon can have as much vertices as the user wants. ROS Mesh has only three aka triangle. http://docs.ros.org/api/shape_msgs/html/msg/Mesh.html
therefore 3

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +      const ITMMesh::Triangle* triangleArray,
pass by reference

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  void extractITMMeshToPolygonMesh(const ITMMesh::Triangle* triangleArray,
pass by reference

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  if (imu_source_ != NULL) delete imu_source_;
use `nullptr`

and this notation:
```C++
if (..) {
  ...
}
```

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  // infinitam is stopped.
?

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  if (true) {
use upper commented line?

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +    std::string filename =
const

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +    std::string filename2 =
use better naming

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +    main_engine_->GetMesh()->WriteOBJ(filename2.c_str());
Do you always want to write both files?

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +    pcl::io::saveOBJFile("../awesome_mesh.obj", *mesh_ptr_);
why are you writing another obj file here?
Are you trying to compare them?

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  ROS_INFO_STREAM("publishMap end!");
remove or update string

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  ROS_INFO_STREAM("publishMap start.");
remove or update string

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  if (triangleArray == NULL) {
nullptr

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  std::size_t nr_triangles = 0;
0u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  std::size_t nr_points = 0;
0u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  nr_points = nr_triangles * 3;
3u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  nr_points = nr_triangles * 3;
Add a comment why this is always *3, as this is not very obvious.

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  point_cloud_pcl->height = 1;
I think height and width are unsigned so: 1u.

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  point_cloud_pcl->is_dense = true;
Are you checking that there are no points set to nan or inf? (Is very likely the case, but double check this)

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  std::size_t point_number = 0;
0u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  for (std::size_t i = 0; i < nr_triangles; ++i) {
0u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  std::size_t v_idx = 0;
0u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  for (uint i = 0; i < nr_triangles; ++i) {
why not size_t?
In any unsigned case: 0u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +    mesh_ptr_->polygons[i].vertices.resize(3);
3u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +    polygon_mesh_ptr->polygons[i].vertices[0] = (i * 3 + 2);
i*3u+2u (here and below)

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
>    point_cloud_pcl->height = 1;
1u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
>    point_cloud_pcl->width = main_engine_->GetMesh()->noTotalTriangles * 3;
3u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
>    ROS_ERROR_COND(main_engine_->GetMesh()->noTotalTriangles < 1,
1u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  std::size_t point_number = 0;
0u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
>    for (int64 i = 0; i < main_engine_->GetMesh()->noTotalTriangles * 3;
why int64?
can this be negative?

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  for (size_t i = 0; i < size; i++, ++pt_iter) {
0u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +  for (size_t i = 0; i < polygon_mesh_ptr->polygons.size(); ++i) {
0u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +    if (polygon_mesh_ptr->polygons[i].vertices.size() < 3) {
3u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +    for (int j = 0; j < 3; ++j) {
size_t, 0u, 3u

2016-12-20 11:30 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +                            rgb_image_filename, Vector2i(320, 240), 0.5f);
Why do we have this set to 320, 240, but I guess this doesn't really matter for now.

2016-12-20 12:03 UTC, ffurrer commented
@gocarlos please make sure to still address the comments that are already outdated by now, I think most of them still apply.

2016-12-20 14:10 UTC, gocarlos commented on InfiniTAM/infinitam_ros_node.cpp
> +  // infinitam is stopped.
one does not get a response, if the service started correctly or not. But one can also turn it off aka shut down infinitam after the mapping etc.

2016-12-20 14:15 UTC, gocarlos commented on InfiniTAM/infinitam_ros_node.cpp
> +    pcl::io::saveOBJFile("../awesome_mesh.obj", *mesh_ptr_);
yes

2016-12-20 14:20 UTC, gocarlos commented on InfiniTAM/infinitam_ros_node.cpp
> +  point_cloud_pcl->is_dense = true;
Object discovery already does this, should I also do that here and iterate through all points?

2016-12-20 14:26 UTC, gocarlos commented on InfiniTAM/infinitam_ros_node.cpp
> +                            rgb_image_filename, Vector2i(320, 240), 0.5f);
this were the default settings, I did not change that, since not using it right now...

2016-12-21 13:33 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +    const ITMMesh::Triangle& triangleArray,
triangle_array

2016-12-21 13:34 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +    const ITMMesh::Triangle& triangleArray,
and I think that there are some more variable names in this file that are not conforming with our standards

2016-12-21 15:21 UTC, gocarlos commented on InfiniTAM/infinitam_ros_node.cpp
> +    const ITMMesh::Triangle& triangleArray,
I'm always confused when to rename or use our standards in part of software that already exists with other standards. I'll try to do that in those files, that I've written.

2016-12-21 15:28 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +    const ITMMesh::Triangle& triangleArray,
well in this file we sticked to our conventions, so at least in this file stick to our conventions. (at least I think so)

2016-12-22 08:19 UTC, ffurrer commented on InfiniTAM/infinitam_ros_node.cpp
> +#include <shape_msgs/Mesh.h>
I don't think you need this twice ;)

2016-12-23 07:49 UTC, martiwer approved these changes

2016-12-23 08:49 UTC, merged